### ISSUE TITLE
To-do list for PurePerms v1.3.0

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PurePerms#105]
### Resources
- [x] messages-tr.yml (Turkish)

### Commands
- [x] Add /addparent + /rmparent
- [x] Add /ppsudo command (NoeulAPI)

### Noeul
- [x] NoeulAPI (https://github.com/PurePlugins/PurePerms/issues/64)

### Provider
- [x] Advanced YAML Provider V2
- [x] MySQL Provider (https://github.com/PurePlugins/PurePerms/commit/1f06b5736041dcb98ed40fd322139b1129538f03)

**Comment by Bamuel** [comment]
:+1:  need mysql

**Comment by Bamuel** [comment]
:+1: need mysql

**Comment by 64FF00** [comment]
@Bamuel Ye :'(

**Comment by AndreyNazarchuk** [comment]
Yes make MySQL as soon as possible, I can help with it.

**Comment by EnderKenji** [comment]
Can Have multi groups on 1 person? Like Lbsg?

**Comment by MCPEPIG** [comment]
Please add per world ranks. Example, someone might have VIP at Spawn, but when they go to prison world, they get A

**Comment by Ad5001** [comment]
@64FF00 Code the **getUsers()** function for a group that will be **REALLY** helpful for developers that want to make extensions (like me xD ) that use PurePerms groups to get players please :)

**Comment by DjJakkiGlass** [comment]
So I should consult Essentials for full list of permission nodes?

**Comment by isoz** [comment]
Hey I put together a phar today for latest version and it complete chaos because you changed from /players/ folder to players.yml, in the future if you think it's doable please include a tool to import all the players/perms inside the folder into MySQL! That would be really boss!

**Comment by 64FF00** [comment]
@Bamuel @AndreyNazarchuk MySQL provider is fully working! Check it out :D

**Comment by 64FF00** [comment]
@EnderKenji Great idea

**Comment by isoz** [comment]
@64FF00 how will I use the latest versions if all my players are inside the players folder instead of the new players.yml file? I can't just start over, theres thousands of players in different groups.

**Comment by 64FF00** [comment]
@isoz Don't worry about it. You only need to set ranks of the players that are not in default groups

**Comment by isoz** [comment]
@64ff00 my server is pretty large a ton of people is not in the default group. I don't know how I will update to the most recent versions because of this.
