### ISSUE TITLE
To-do list for PurePerms v1.1.0

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PurePerms#15]
### plugin.yml
- [x] API Version Bump

### Main Folder
- [x] Improved default message resource, including logger messages
- [x] Improved updatePermissions() API function

### Event
- [x] PPGroupChangedEvent (For checking user group changes)

### Provider
- [x] SQLite3Provider (Experimental)

**Comment by wsj7178** [comment]
inheritance 를 명령어로는 추가 못하나요?

**Comment by 64FF00** [comment]
@wsj7178 나중에 추가할 예정이예요 ;D

**Comment by MegaSamNinja** [comment]
Can you add MySQL support to the people who has ranks

**Comment by 64FF00** [comment]
@MegaSamNinja Will be added in v1.2.0!

**Comment by 64FF00** [comment]
@yungtechboy1 Ta-da!

**Comment by 64FF00** [comment]
@yungtechboy1 TRUE!

**Comment by Briarlake** [comment]
Question: How do you add name prefixes for groups? I have been on other servers that use PurePerms, and the group shows a prefix before their name. Is it possible you know why?

**Comment by MCPEPIG** [comment]
@Briarlake Use PureChat

**Comment by Briarlake** [comment]
What commands do you use in PureChat?

**Comment by MCPEPIG** [comment]
No commands

**Comment by Briarlake** [comment]
Okay. Thx

**Comment by Briarlake** [comment]
:D

**Comment by MCPEPIG** [comment]
To edit chat format go to the config for OureChat

**Comment by MCPEPIG** [comment]
No problem

**Comment by Briarlake** [comment]
K

**Comment by JoahDave** [comment]
Love it!

**Comment by PEMapModder** [comment]
Siggestion: web interface

**Comment by 64FF00** [comment]
@PEMapModder Like what? That sounds really cool though...

**Comment by PEMapModder** [comment]
Likke @Falkirks' Vault

**Comment by Xesame** [comment]
64FF00님
플러그인 파일 전체를 지우고 월드를 지우고
플레이어 데이터를 지우고 플러그인을 지워도
자꾸 칭호가 none로 뜹니다
오늘 10시부터 4시간동안 계속해봤는데 안되더라구요...
한번만 살펴봐주세요

**Comment by 64FF00** [comment]
@Xesame 여기다 글 쓰지 마시고 새로운 이슈로 하나 만들어주세요!

**Comment by 64FF00** [comment]
I'm really sorry to have to tell you that MySQL data provider won't be included in this release due to the lack of time. It might be added in next v1.1.x releases instead. Once again... thanks for your understanding... :'( *crying*
