### ISSUE TITLE
To-do list for PurePerms v1.4.0

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PurePerms#177]
### Main Folder
- [x] Rank Constraints (#121)
- [ ] YAML to MySQL converter? (#134 #277)
- [ ] YAML-OLD to YAML-NEW converter
- [ ] Purge Command? (#213)
- [ ] Fix LOW TPS (#191)

**Comment by isoz** [comment]
YAML to MySQL please, my server can't grow past 200 players because of lag and I'm unable to add more servers as I don't know how I can possibly share the YAML folder with the second server. Theres thousands of people with different ranks, I can't start from zero.

**Comment by MrDoni98** [comment]
If the player in a default group in the database is not logged?

**Comment by 64FF00** [comment]
@MrDoni98 Will not store a player in default groups unless he gets user permissions

**Comment by MrDoni98** [comment]
@64FF00  ok thanks.That's all I wanted to know

**Comment by 64FF00** [comment]
@MrDoni98 :heart_decoration:

**Comment by MrDoni98** [comment]
@64FF00 What did you mean?

**Comment by 0-Eclipse-0** [comment]
Oops mean't to click comment. Sorry

**Comment by Pub4Game** [comment]
@64FF00 Can you make PP and PC for Nukkit? I like your plugins and I would like to see them for Nukkit.

**Comment by ModdingTwinz** [comment]
@64FF00 There A Bug With The PurePerms & PureChat Where The Groups Don't Show In Chat At All Is There Anyway You Can Fix The Bug?

**Comment by ModdingTwinz** [comment]
@64FF00 I'm Trying To Open A Pocketmine Server But I Need The Groups To Work Please Help.

**Comment by QimieGaming** [comment]
Can u make the plugin can connect and share MySQLite3 with many server. Please make a secret command or something to prevent Database/Data Leaks.

**Comment by jasonwynn10** [comment]
@Borduni @64FF00 Would you mind if I removed Noeul from PurePerms? It doesn't work and it doesn't appear to fit correctly into a permission plugin when it should be in an auth plugin

**Comment by NanoRayYT** [comment]
Fix expire time for mysql

**Comment by isoz** [comment]
A "add to group" command in addition to setgroup, this would make it easier to setup a prison server since 1 user could be part of multiple groups, which is how PEX in PC does.
