### ISSUE TITLE
To-do list for PurePerms v1.2.0

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PurePerms#30]
### Main Folder
- [x] Add UserDataMgr class instead of the old PPUser class (API Rewrite)
- [x] Fix major UUID issues (#90)

### Provider
- [x] Advanced YAML Provider

**Comment by Bamuel** [comment]
:grinning: 

I hope you get MySQL Provider soon

**Comment by Bamuel** [comment]
https://github.com/PocketMine/SimpleAuth/blob/master/src/SimpleAuth/provider/MySQLDataProvider.php
https://github.com/PocketMine/SimpleAuth/blob/master/src/SimpleAuth/task/MySQLPingTask.php
https://github.com/PocketMine/SimpleAuth/blob/master/resources/mysql.sql

This will help you set up a MySQL provider.

I just hope you can get MySQL working :octocat:

**Comment by 64FF00** [comment]
@Bamuel Thanks a lot, but I think I would be able to work on it after I finish my finals :'(

**Comment by 64FF00** [comment]
@onebone Can you please do the Japanese lang file related stuff
일본어 파일 작업 해주실수 있나요

**Comment by onebone** [comment]
@6400FF 물론입니다

**Comment by 64FF00** [comment]
@onebone 6400FF는 보라색인디유

**Comment by 64FF00** [comment]
@onebone Please make a PR when ready

**Comment by onebone** [comment]
@64FF00 사실 제가 보라색을 좋아합니다

**Comment by 64FF00** [comment]
@onebone 딴소리긴 한데 요새 이프팀 레포 활동이 뜸해진건 기분탓?

**Comment by onebone** [comment]
@64FF00 그거 아마 원래 hm님이 커밋 엄청 하셨는데 지금 비공개로 전환하셔서 그럴걸요

**Comment by 64FF00** [comment]
@onebone 그럼 초록색은요? :heart:

**Comment by 64FF00** [comment]
@onebone ㅇㅎ

**Comment by 64FF00** [comment]
@onebone Tysm for your help btw

**Comment by 64FF00** [comment]
@onebone 흐흐 이참에 한국어 파일에 장난좀 쳐볼까요

**Comment by 64FF00** [comment]
Japanese language resource file has been added to PurePerms. Check this out: https://github.com/PurePlugins/PurePerms/commit/513f27e419a77aa2f3b9851cf38437ef5ee1fa60 (Thanks to @onebone, <3)

**Comment by 64FF00** [comment]
@PEMapModder Could you please help me to get a Chinese lang resource? Ehehehehh

**Comment by 64FF00** [comment]
@shoghicp (Just joking) / @iksaku #SpanishLangResource

**Comment by legoboy0215** [comment]
lol He does traditional but those Chinese will say: "Why no simplified chinese?

**Comment by Pub4Game** [comment]
Can add the issuance of the group at the time? /setgroup Pub4Game 30 day VIP

**Comment by 64FF00** [comment]
@Pub4Game Try using TimeRanks by @luca28pet

**Comment by Pub4Game** [comment]
Thanks

**Comment by Pub4Game** [comment]
Oh no, I wanted to group stood out on the day, week, month

**Comment by PEMapModder** [comment]
@legoboy0215 you know that in Hong Kong simplified/traditional Chinese is a sensitive issue. There was once an app that only had simplified Chinese translation and got many negative comments as "trying to please mainland people".

**Comment by 64FF00** [comment]
@PEMapModder Then what about adding both of them if available heheh

**Comment by PEMapModder** [comment]
Actually, Google Translate is already good enough to translate between the two.

**Comment by iksaku** [comment]
@64FF00 I would be glad to help with the MySQL provider ;)

**Comment by legoboy0215** [comment]
@PEMapModder ol. I do not have the issue of that kind. But yes, it is sometimes not so fair.

**Comment by 64FF00** [comment]
@iksaku Yey <3

**Comment by jaciel14** [comment]
Good Job

**Comment by iksaku** [comment]
@64FF00 So, green light for me to implement it?

**Comment by 64FF00** [comment]
@iksaku :+1:

**Comment by tylrng** [comment]
I can help you with both Traditional Chinese and Simplified Chinese.

**Comment by Pub4Game** [comment]
Good job! :+1:
